$ErrorActionPreference = 'Stop'
try { [Console]::OutputEncoding = [Text.Encoding]::UTF8 } catch { }
$out = [ordered]@{ powershell = $PSVersionTable.PSVersion.ToString() }; $clientArea = @(833, 90, 1727, 1459, 192)
function Test-Old($box) { try { if ($clientArea[4] -ne 192 -or $clientArea[2] - $clientArea[0] -ne $box.viewport[0] * $box.dpr -or $clientArea[3] - $clientArea[1] -ne $box.viewport[1] * $box.dpr -or $box.x -le 0 -or $box.x -ge $box.viewport[0] -or $box.y -le 0 -or $box.y -ge $box.viewport[1]) { throw 'owned control client and browser geometry disagree' } ; return 'pass' } catch { return 'refused: ' + $_.Exception.Message } }
function Test-New($box) { $entry = [ordered]@{}; try { $entry.control_box = [ordered]@{ viewport = @($box.viewport); dpr = $box.dpr; x = $box.x; y = $box.y; width = $box.width; height = $box.height; shown = $box.shown } ; if ($clientArea[4] -ne 192 -or [Math]::Abs(($clientArea[2] - $clientArea[0]) - $box.viewport[0] * $box.dpr) -ge $box.dpr -or [Math]::Abs(($clientArea[3] - $clientArea[1]) - $box.viewport[1] * $box.dpr) -ge $box.dpr -or $box.x -le 0 -or $box.x -ge $box.viewport[0] -or $box.y -le 0 -or $box.y -ge $box.viewport[1]) { throw 'owned control client and browser geometry disagree' } ; return 'pass ' + ($entry.control_box | ConvertTo-Json -Compress) } catch { return 'refused: ' + $_.Exception.Message + ' ' + ($entry.control_box | ConvertTo-Json -Compress) } }
$cases = [ordered]@{ h684 = '{"x":223.5,"y":300,"width":400,"height":60,"viewport":[447,684],"dpr":2,"shown":true}'; h685 = '{"x":223.5,"y":300,"width":400,"height":60,"viewport":[447,685],"dpr":2,"shown":true}'; h683 = '{"x":223.5,"y":300,"width":400,"height":60,"viewport":[447,683],"dpr":2,"shown":true}'; h686 = '{"x":223.5,"y":300,"width":400,"height":60,"viewport":[447,686],"dpr":2,"shown":true}'; w446 = '{"x":223.5,"y":300,"width":400,"height":60,"viewport":[446,684],"dpr":2,"shown":true}'; xout = '{"x":447,"y":300,"width":400,"height":60,"viewport":[447,684],"dpr":2,"shown":true}' }
$out.cases = [ordered]@{}; foreach ($k in $cases.Keys) { $box = $cases[$k] | ConvertFrom-Json; $out.cases[$k] = [ordered]@{ old = (Test-Old $box); new = (Test-New $box) } }
$e = $null; $t = $null; $f = [Management.Automation.Language.Parser]::ParseFile('\\wsl.localhost\Ubuntu\home\agentsdock\Projects\learning-companion\wt-review\docs\verification\qa\p0-13-tts-52be105\candidate-r4-20261009\runner.ps1', [ref]$t, [ref]$e)
$arith = 'Plus', 'Minus', 'Multiply', 'Divide', 'Rem'; $hits = $f.FindAll({ param($n) $n -is [Management.Automation.Language.BinaryExpressionAst] -and $arith -contains [string]$n.Operator -and ($n.Left -is [Management.Automation.Language.ArrayLiteralAst] -or $n.Right -is [Management.Automation.Language.ArrayLiteralAst]) }, $true)
$fn = $f.Find({ param($n) $n -is [Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Assert-QaProductPlacement' }, $true); $out.r4_runner = [ordered]@{ parse_errors = @($e).Count; array_arith_hits = @($hits).Count; product_placement_assigns = @($fn.FindAll({ param($n) $n -is [Management.Automation.Language.AssignmentStatementAst] -and $n.Left -is [Management.Automation.Language.VariableExpressionAst] }, $true) | ForEach-Object { $_.Left.VariablePath.UserPath } | Sort-Object -Unique) }
$out | ConvertTo-Json -Depth 6
