import Foundation
import XCTest

// Linux harness only: a dead child's pipe must not kill the interpreter (Darwin uses F_SETNOSIGPIPE/SO_NOSIGPIPE).
signal(SIGPIPE, SIG_IGN)
let selected = ProcessInfo.processInfo.environment["LC_TESTS"] ?? "link"
typealias Entry = (String, (DesktopCaptureTests) -> () throws -> Void)
let linkTests: [Entry] = [
    ("testCaptureHostConfigurationAndStartupRecordKeepSecretsPrivate", DesktopCaptureTests.testCaptureHostConfigurationAndStartupRecordKeepSecretsPrivate),
    ("testHostChildGetsOnlyAPrivatePipeAndEndsOnEOF", asyncTest(DesktopCaptureTests.testHostChildGetsOnlyAPrivatePipeAndEndsOnEOF)),
    ("testLinkStoresRetainedFramesAndStopsTheStream", asyncTest(DesktopCaptureTests.testLinkStoresRetainedFramesAndStopsTheStream)),
    ("testStopRacesKeepDoubtAndNeverRegisterAfterStop", asyncTest(DesktopCaptureTests.testStopRacesKeepDoubtAndNeverRegisterAfterStop)),
    ("testRestartReconcilesWithoutReplayOrRestart", asyncTest(DesktopCaptureTests.testRestartReconcilesWithoutReplayOrRestart)),
    ("testServiceWithdrawalEndsLocalCapture", asyncTest(DesktopCaptureTests.testServiceWithdrawalEndsLocalCapture)),
    ("testDamagedLinkRecordIsKeptAndNeverUsed", asyncTest(DesktopCaptureTests.testDamagedLinkRecordIsKeptAndNeverUsed)),
    ("testRecordWritesAreCompleteBeforeTheyReplace", DesktopCaptureTests.testRecordWritesAreCompleteBeforeTheyReplace),
    ("testUnwritableRecordSendsNoStopAndKeepsOutcomes", asyncTest(DesktopCaptureTests.testUnwritableRecordSendsNoStopAndKeepsOutcomes)),
    ("testNewStreamsNameTheSettledPredecessor", asyncTest(DesktopCaptureTests.testNewStreamsNameTheSettledPredecessor)),
    ("testStopDuringStartSettlementShowsTheSettledState", asyncTest(DesktopCaptureTests.testStopDuringStartSettlementShowsTheSettledState)),
    ("testChildLossReconnectsWithoutConsentAndStopsOnce", asyncTest(DesktopCaptureTests.testChildLossReconnectsWithoutConsentAndStopsOnce)),
    ("testNoRegistrationAttemptAfterStop", asyncTest(DesktopCaptureTests.testNoRegistrationAttemptAfterStop)),
    ("testFailedSpawnIsAbandonedAndNeverReconciled", asyncTest(DesktopCaptureTests.testFailedSpawnIsAbandonedAndNeverReconciled)),
    ("testRecordFaultFencesEveryLaterRequest", asyncTest(DesktopCaptureTests.testRecordFaultFencesEveryLaterRequest)),
    ("testReopenedStopReusesItsRecordedCommand", asyncTest(DesktopCaptureTests.testReopenedStopReusesItsRecordedCommand)),
    ("testLaterRefusalKeepsAnEarlierControlDoubt", asyncTest(DesktopCaptureTests.testLaterRefusalKeepsAnEarlierControlDoubt)),
    ("testLostAnswerThenRefusalStaysUnknownInTheLink", asyncTest(DesktopCaptureTests.testLostAnswerThenRefusalStaysUnknownInTheLink)),
    ("testStopAfterDoubtRenewsTheBearerAndKeepsTheDoubt", asyncTest(DesktopCaptureTests.testStopAfterDoubtRenewsTheBearerAndKeepsTheDoubt)),
    ("testSourceInDoubtThenRefusedEndsTheCaptureWithoutClaimingItWasNotRegistered", asyncTest(DesktopCaptureTests.testSourceInDoubtThenRefusedEndsTheCaptureWithoutClaimingItWasNotRegistered)),
    ("testServerEndInARegistrationReplayEndsTheCaptureDespiteARecordFault", asyncTest(DesktopCaptureTests.testServerEndInARegistrationReplayEndsTheCaptureDespiteARecordFault)),
    ("testReconnectReplayActsOnABelievedServerEndOrLostPermission", asyncTest(DesktopCaptureTests.testReconnectReplayActsOnABelievedServerEndOrLostPermission)),
    ("testPendingFramesAreShownAtOnceAndStoredOnlyAfterTheirACK", asyncTest(DesktopCaptureTests.testPendingFramesAreShownAtOnceAndStoredOnlyAfterTheirACK)),
    ("testBatchWithoutABelievedAnswerStaysNotKnownUntilItsExactACK", asyncTest(DesktopCaptureTests.testBatchWithoutABelievedAnswerStaysNotKnownUntilItsExactACK)),
    ("testStopOrARecordFaultNeverShowsTheLinkAsUpAndEndsWithNothingAwaiting", asyncTest(DesktopCaptureTests.testStopOrARecordFaultNeverShowsTheLinkAsUpAndEndsWithNothingAwaiting)),
    ("testResendIntentIsRecordedShownAndFenced", asyncTest(DesktopCaptureTests.testResendIntentIsRecordedShownAndFenced)),
    ("testOriginalsOfAnUnsentBatchAreReportedAsAlreadyAccepted", asyncTest(DesktopCaptureTests.testOriginalsOfAnUnsentBatchAreReportedAsAlreadyAccepted)),
    ("testLoopbackTransportOnARealSocket", asyncTest(DesktopCaptureTests.testLoopbackTransportOnARealSocket)),
]
let upload: [Entry] = [
    ("testPreparesTheExactMacBatchWithImmutableInkReferences", DesktopCaptureTests.testPreparesTheExactMacBatchWithImmutableInkReferences),
    ("testUploadsEveryOriginalThenTheExactBatch", asyncTest(DesktopCaptureTests.testUploadsEveryOriginalThenTheExactBatch)),
    ("testUnbelievedAnswersStayInDoubtAndResendTheSameBytes", asyncTest(DesktopCaptureTests.testUnbelievedAnswersStayInDoubtAndResendTheSameBytes)),
    ("testTypedRefusalsAndDependencies", asyncTest(DesktopCaptureTests.testTypedRefusalsAndDependencies)),
    ("testStopCancellationAndExpiryPreventNewSends", asyncTest(DesktopCaptureTests.testStopCancellationAndExpiryPreventNewSends)),
    ("testLocalRefusalsSendNothing", asyncTest(DesktopCaptureTests.testLocalRefusalsSendNothing)),
    ("testLoopbackTransportSendsExactHeadersAndNeverFollowsRedirects", asyncTest(DesktopCaptureTests.testLoopbackTransportSendsExactHeadersAndNeverFollowsRedirects)),
    ("testUTCTimestampsFollowTheReleasedRule", DesktopCaptureTests.testUTCTimestampsFollowTheReleasedRule),
]
let everything: [Entry] = [
    ("testCaptureHostConfigurationAndStartupRecordKeepSecretsPrivate", DesktopCaptureTests.testCaptureHostConfigurationAndStartupRecordKeepSecretsPrivate),
    ("testHostChildGetsOnlyAPrivatePipeAndEndsOnEOF", asyncTest(DesktopCaptureTests.testHostChildGetsOnlyAPrivatePipeAndEndsOnEOF)),
    ("testLinkStoresRetainedFramesAndStopsTheStream", asyncTest(DesktopCaptureTests.testLinkStoresRetainedFramesAndStopsTheStream)),
    ("testStopRacesKeepDoubtAndNeverRegisterAfterStop", asyncTest(DesktopCaptureTests.testStopRacesKeepDoubtAndNeverRegisterAfterStop)),
    ("testRestartReconcilesWithoutReplayOrRestart", asyncTest(DesktopCaptureTests.testRestartReconcilesWithoutReplayOrRestart)),
    ("testServiceWithdrawalEndsLocalCapture", asyncTest(DesktopCaptureTests.testServiceWithdrawalEndsLocalCapture)),
    ("testDamagedLinkRecordIsKeptAndNeverUsed", asyncTest(DesktopCaptureTests.testDamagedLinkRecordIsKeptAndNeverUsed)),
    ("testRecordWritesAreCompleteBeforeTheyReplace", DesktopCaptureTests.testRecordWritesAreCompleteBeforeTheyReplace),
    ("testUnwritableRecordSendsNoStopAndKeepsOutcomes", asyncTest(DesktopCaptureTests.testUnwritableRecordSendsNoStopAndKeepsOutcomes)),
    ("testNewStreamsNameTheSettledPredecessor", asyncTest(DesktopCaptureTests.testNewStreamsNameTheSettledPredecessor)),
    ("testStopDuringStartSettlementShowsTheSettledState", asyncTest(DesktopCaptureTests.testStopDuringStartSettlementShowsTheSettledState)),
    ("testChildLossReconnectsWithoutConsentAndStopsOnce", asyncTest(DesktopCaptureTests.testChildLossReconnectsWithoutConsentAndStopsOnce)),
    ("testNoRegistrationAttemptAfterStop", asyncTest(DesktopCaptureTests.testNoRegistrationAttemptAfterStop)),
    ("testFailedSpawnIsAbandonedAndNeverReconciled", asyncTest(DesktopCaptureTests.testFailedSpawnIsAbandonedAndNeverReconciled)),
    ("testRecordFaultFencesEveryLaterRequest", asyncTest(DesktopCaptureTests.testRecordFaultFencesEveryLaterRequest)),
    ("testReopenedStopReusesItsRecordedCommand", asyncTest(DesktopCaptureTests.testReopenedStopReusesItsRecordedCommand)),
    ("testLaterRefusalKeepsAnEarlierControlDoubt", asyncTest(DesktopCaptureTests.testLaterRefusalKeepsAnEarlierControlDoubt)),
    ("testLostAnswerThenRefusalStaysUnknownInTheLink", asyncTest(DesktopCaptureTests.testLostAnswerThenRefusalStaysUnknownInTheLink)),
    ("testStopAfterDoubtRenewsTheBearerAndKeepsTheDoubt", asyncTest(DesktopCaptureTests.testStopAfterDoubtRenewsTheBearerAndKeepsTheDoubt)),
    ("testSourceInDoubtThenRefusedEndsTheCaptureWithoutClaimingItWasNotRegistered", asyncTest(DesktopCaptureTests.testSourceInDoubtThenRefusedEndsTheCaptureWithoutClaimingItWasNotRegistered)),
    ("testServerEndInARegistrationReplayEndsTheCaptureDespiteARecordFault", asyncTest(DesktopCaptureTests.testServerEndInARegistrationReplayEndsTheCaptureDespiteARecordFault)),
    ("testReconnectReplayActsOnABelievedServerEndOrLostPermission", asyncTest(DesktopCaptureTests.testReconnectReplayActsOnABelievedServerEndOrLostPermission)),
    ("testPendingFramesAreShownAtOnceAndStoredOnlyAfterTheirACK", asyncTest(DesktopCaptureTests.testPendingFramesAreShownAtOnceAndStoredOnlyAfterTheirACK)),
    ("testBatchWithoutABelievedAnswerStaysNotKnownUntilItsExactACK", asyncTest(DesktopCaptureTests.testBatchWithoutABelievedAnswerStaysNotKnownUntilItsExactACK)),
    ("testStopOrARecordFaultNeverShowsTheLinkAsUpAndEndsWithNothingAwaiting", asyncTest(DesktopCaptureTests.testStopOrARecordFaultNeverShowsTheLinkAsUpAndEndsWithNothingAwaiting)),
    ("testResendIntentIsRecordedShownAndFenced", asyncTest(DesktopCaptureTests.testResendIntentIsRecordedShownAndFenced)),
    ("testOriginalsOfAnUnsentBatchAreReportedAsAlreadyAccepted", asyncTest(DesktopCaptureTests.testOriginalsOfAnUnsentBatchAreReportedAsAlreadyAccepted)),
    ("testLoopbackTransportOnARealSocket", asyncTest(DesktopCaptureTests.testLoopbackTransportOnARealSocket)),
    ("testFactsAreReadFromSampleBufferAttachments", DesktopCaptureTests.testFactsAreReadFromSampleBufferAttachments),
    ("testMissingOrUnknownFactsStayUnknown", DesktopCaptureTests.testMissingOrUnknownFactsStayUnknown),
    ("testNewPixelsAreKeptAsTheExactUnrotatedPNG", DesktopCaptureTests.testNewPixelsAreKeptAsTheExactUnrotatedPNG),
    ("testStatusesRunsAndGapsAreRecorded", DesktopCaptureTests.testStatusesRunsAndGapsAreRecorded),
    ("testStatusOnlyAndUnknownCallbacksClearCurrentPixels", DesktopCaptureTests.testStatusOnlyAndUnknownCallbacksClearCurrentPixels),
    ("testCompleteWithoutImageIsAGapNotNewPixels", DesktopCaptureTests.testCompleteWithoutImageIsAGapNotNewPixels),
    ("testNothingIsKeptOrLiveAfterLiveClaimsEnd", DesktopCaptureTests.testNothingIsKeptOrLiveAfterLiveClaimsEnd),
    ("testSilenceBeforeTheEndIsAGap", DesktopCaptureTests.testSilenceBeforeTheEndIsAGap),
    ("testFreshnessNeedsARecentCallback", DesktopCaptureTests.testFreshnessNeedsARecentCallback),
    ("testDelayedSampleIsNotLive", DesktopCaptureTests.testDelayedSampleIsNotLive),
    ("testFrameAdmittedBeforeStopIsKeptAndNothingAfter", DesktopCaptureTests.testFrameAdmittedBeforeStopIsKeptAndNothingAfter),
    ("testStopWhileListingDisplaysCreatesNothing", asyncTest(DesktopCaptureTests.testStopWhileListingDisplaysCreatesNothing)),
    ("testStopWhileTheStreamStartsStopsIt", asyncTest(DesktopCaptureTests.testStopWhileTheStreamStartsStopsIt)),
    ("testStartOutcomes", asyncTest(DesktopCaptureTests.testStartOutcomes)),
    ("testNewPixelsBeyondTheBudgetAreNotKept", DesktopCaptureTests.testNewPixelsBeyondTheBudgetAreNotKept),
    ("testWritesSampleSessionForMapping", DesktopCaptureTests.testWritesSampleSessionForMapping),
    ("testLiveGateKeepsTheFirstClosureAndAdmitsNothingAfterIt", DesktopCaptureTests.testLiveGateKeepsTheFirstClosureAndAdmitsNothingAfterIt),
    ("testStopReasonsKeepTheOriginalError", DesktopCaptureTests.testStopReasonsKeepTheOriginalError),
    ("testSessionsNeverShareADirectory", DesktopCaptureTests.testSessionsNeverShareADirectory),
    ("testFrameStoreIsTheReviewedScreenObserverCopy", DesktopCaptureTests.testFrameStoreIsTheReviewedScreenObserverCopy),
    ("testMapsRetainedFramesToDesktopFrames", DesktopCaptureTests.testMapsRetainedFramesToDesktopFrames),
    ("testPreparesRequestsAndWritesFixtures", DesktopCaptureTests.testPreparesRequestsAndWritesFixtures),
    ("testRefusesUnrepresentableDataAndKeepsOriginals", DesktopCaptureTests.testRefusesUnrepresentableDataAndKeepsOriginals),
    ("testReaderRefusesAlteredEscapingAndUnreadableOriginals", DesktopCaptureTests.testReaderRefusesAlteredEscapingAndUnreadableOriginals),
    ("testReaderRefusesSymbolicLinksForOriginals", DesktopCaptureTests.testReaderRefusesSymbolicLinksForOriginals),
    ("testReaderRefusesRecognizedEventsWithoutPayload", DesktopCaptureTests.testReaderRefusesRecognizedEventsWithoutPayload),
    ("testDesktopJSONIsStrictStandardJSON", DesktopCaptureTests.testDesktopJSONIsStrictStandardJSON),
    ("testComposedImagesDrawTheInkCommittedWhenThePixelsWereOnScreen", DesktopCaptureTests.testComposedImagesDrawTheInkCommittedWhenThePixelsWereOnScreen),
    ("testEveryKeptFrameGetsOneCompositionOutcomeBeforeTheEnding", DesktopCaptureTests.testEveryKeptFrameGetsOneCompositionOutcomeBeforeTheEnding),
    ("testCompositionRefusalsAndFailuresKeepRawOriginalsAndSayWhy", DesktopCaptureTests.testCompositionRefusalsAndFailuresKeepRawOriginalsAndSayWhy),
    ("testAskTextInAnAppExcludedSessionMakesNoUnverifiedClaim", DesktopCaptureTests.testAskTextInAnAppExcludedSessionMakesNoUnverifiedClaim),
    ("testVisibleStrokesReplayEveryCommittedRevision", DesktopCaptureTests.testVisibleStrokesReplayEveryCommittedRevision),
    ("testFrozenInkOriginalKeepsTheExactDocumentAndItsHistory", DesktopCaptureTests.testFrozenInkOriginalKeepsTheExactDocumentAndItsHistory),
    ("testInkOriginalFailuresLeaveEntriesUntouchedAndSayWhy", DesktopCaptureTests.testInkOriginalFailuresLeaveEntriesUntouchedAndSayWhy),
    ("testStopAndReopenKeepOriginalsAndOldSessionsStayUnknown", DesktopCaptureTests.testStopAndReopenKeepOriginalsAndOldSessionsStayUnknown),
    ("testWriteEraseUndoAndRedoKeepEveryStroke", DesktopCaptureTests.testWriteEraseUndoAndRedoKeepEveryStroke),
    ("testErasingCutsTheDrawnLineBetweenSparseSamples", DesktopCaptureTests.testErasingCutsTheDrawnLineBetweenSparseSamples),
    ("testMouseWritingNeedsItsSwitchAndPenFactsAreKept", DesktopCaptureTests.testMouseWritingNeedsItsSwitchAndPenFactsAreKept),
    ("testAskRestoresThePreviousModeAndRecordsTheFrameRegion", DesktopCaptureTests.testAskRestoresThePreviousModeAndRecordsTheFrameRegion),
    ("testAskKeepsAnActualCropOfTheExactRetainedOriginal", DesktopCaptureTests.testAskKeepsAnActualCropOfTheExactRetainedOriginal),
    ("testAskFinishCropsThePinnedFrameNotALaterOne", DesktopCaptureTests.testAskFinishCropsThePinnedFrameNotALaterOne),
    ("testClosingInputKeepsTheStrokeInProgressAndRefusesNewInput", DesktopCaptureTests.testClosingInputKeepsTheStrokeInProgressAndRefusesNewInput),
    ("testInkIsSavedAtomicallyReopenedAndEditedWithoutReplacingOtherFiles", DesktopCaptureTests.testInkIsSavedAtomicallyReopenedAndEditedWithoutReplacingOtherFiles),
    ("testReopenFindsAndLoadsNewerConflictCopies", DesktopCaptureTests.testReopenFindsAndLoadsNewerConflictCopies),
    ("testUnsavedInkIsHeldUntilSavedExportedOrDiscarded", DesktopCaptureTests.testUnsavedInkIsHeldUntilSavedExportedOrDiscarded),
    ("testPreparesTheExactMacBatchWithImmutableInkReferences", DesktopCaptureTests.testPreparesTheExactMacBatchWithImmutableInkReferences),
    ("testUploadsEveryOriginalThenTheExactBatch", asyncTest(DesktopCaptureTests.testUploadsEveryOriginalThenTheExactBatch)),
    ("testUnbelievedAnswersStayInDoubtAndResendTheSameBytes", asyncTest(DesktopCaptureTests.testUnbelievedAnswersStayInDoubtAndResendTheSameBytes)),
    ("testTypedRefusalsAndDependencies", asyncTest(DesktopCaptureTests.testTypedRefusalsAndDependencies)),
    ("testStopCancellationAndExpiryPreventNewSends", asyncTest(DesktopCaptureTests.testStopCancellationAndExpiryPreventNewSends)),
    ("testLocalRefusalsSendNothing", asyncTest(DesktopCaptureTests.testLocalRefusalsSendNothing)),
    ("testLoopbackTransportSendsExactHeadersAndNeverFollowsRedirects", asyncTest(DesktopCaptureTests.testLoopbackTransportSendsExactHeadersAndNeverFollowsRedirects)),
    ("testUTCTimestampsFollowTheReleasedRule", DesktopCaptureTests.testUTCTimestampsFollowTheReleasedRule),
    ("testMapsEveryRetainedOutcomeToMacFrameMetadata", DesktopCaptureTests.testMapsEveryRetainedOutcomeToMacFrameMetadata),
    ("testIncompleteSessionsNeverImplyEmptyInkOrLiveState", DesktopCaptureTests.testIncompleteSessionsNeverImplyEmptyInkOrLiveState),
]
var chosen: [Entry] = []
if selected.contains("link") { chosen += linkTests }
if selected.contains("upload") { chosen += upload }
if selected.contains("all") { chosen += everything }
if selected.contains("probe") { chosen += [("testProbeRealHost", asyncTest(DesktopCaptureTests.testProbeRealHost))] }
if selected.contains("memory") { chosen += [("testProbeMemoryHost", asyncTest(DesktopCaptureTests.testProbeMemoryHost))] }
if let only = ProcessInfo.processInfo.environment["LC_ONLY"] { chosen = chosen.filter { only.split(separator: ",").map(String.init).contains($0.0) } }
XCTMain([testCase(chosen)])
