// GENERATED by apps/safari-extension/scripts/build-webextension.mjs from apps/safari-extension/src.
// Do not edit: change the TypeScript sources and rebuild (check with --check).
// Modules (dependency order): src/ink.js, src/ink-worker.js
(() => {
'use strict';
const factories = new Map();
const cache = new Map();
const require = (id) => {
  if (cache.has(id)) return cache.get(id);
  const exports = {};
  cache.set(id, exports);
  factories.get(id)(exports, require);
  return exports;
};
factories.set("apps/safari-extension/src/ink.js", (exports, require) => {
// Editable WRITE ink for one page: strokes, partial erase, undo and redo, and a JSON document that
// keeps the originals (lc-web-ink/v1, a web-local format, not a shared contract). DOM-free.
//
// - An erase never deletes a stroke: the stroke leaves the visible set and the pieces that survive
//   the eraser are added as new strokes `derived_from` it. The history links both, so undo, redo and a
//   later export can return to every original.
// - Undo and redo stacks are not stored; they are rebuilt by replaying the history, so a reopened
//   document edits exactly as before. A new edit after an undo starts a branch: the history keeps the
//   undone operations, only the redo stack is cleared.
// - The visible strokes are kept in drawing order: the order their original strokes were written in.
//   Pieces of an erased stroke take its place, so erase, undo and redo never restack the ink.
const INK_FORMAT = 'lc-web-ink/v1';
const emptyInk = (page) => ({ format: INK_FORMAT, page, revision: 0, strokes: {}, visible: [], history: [] });
/** The undo and redo stacks (sequence numbers of add/erase operations), rebuilt from the history. */
function stacks(doc) {
    const undo = [];
    let redo = [];
    for (const op of doc.history) {
        if (op.op === 'add' || op.op === 'erase') {
            undo.push(op.seq);
            redo = [];
        }
        else if (op.op === 'undo') {
            const target = undo.pop();
            if (target !== undefined)
                redo.push(target);
        }
        else {
            const target = redo.pop();
            if (target !== undefined)
                undo.push(target);
        }
    }
    return { undo, redo };
}
/**
 * Drawing order: by the time the stroke's original (itself, or the stroke its piece derives from) was
 * first added, then by the time the piece itself was.
 */
function drawingOrder(ids, strokes, history) {
    const first = new Map();
    for (const op of history)
        for (const id of op.added)
            if (!first.has(id))
                first.set(id, first.size);
    const at = (id) => first.get(id) ?? Number.MAX_SAFE_INTEGER;
    const root = (id) => strokes[id]?.derived_from ?? id;
    return [...ids].sort((a, b) => at(root(a)) - at(root(b)) || at(a) - at(b));
}
const apply = (doc, op, strokes = doc.strokes) => {
    const seq = doc.history.length === 0 ? 1 : doc.history[doc.history.length - 1].seq + 1;
    const history = [...doc.history, { ...op, seq }];
    const shown = new Set(doc.visible);
    for (const id of op.removed)
        shown.delete(id);
    for (const id of op.added)
        shown.add(id);
    return { ...doc, revision: doc.revision + 1, strokes, visible: drawingOrder(shown, strokes, history), history };
};
function addStroke(doc, stroke, at) {
    if (doc.strokes[stroke.id])
        throw new Error(`stroke ${stroke.id} already exists`);
    return apply(doc, { at, op: 'add', added: [stroke.id], removed: [] }, { ...doc.strokes, [stroke.id]: stroke });
}
/** Points no farther apart than `step`, interpolating time and pressure (so a thin eraser cannot slip between points). */
function densify(points, step) {
    const out = [];
    points.forEach((p, i) => {
        if (i > 0) {
            const q = points[i - 1];
            const n = Math.floor(Math.hypot(p[0] - q[0], p[1] - q[1]) / step);
            for (let k = 1; k <= n; k++) {
                const f = k / (n + 1);
                out.push([q[0] + (p[0] - q[0]) * f, q[1] + (p[1] - q[1]) * f, q[2] + (p[2] - q[2]) * f, q[3] + (p[3] - q[3]) * f]);
            }
        }
        out.push(p);
    });
    return out;
}
const segmentDistance = (p, a, b) => {
    const dx = b[0] - a[0];
    const dy = b[1] - a[1];
    const len = dx * dx + dy * dy;
    const t = len === 0 ? 0 : Math.max(0, Math.min(1, ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / len));
    return Math.hypot(p[0] - (a[0] + t * dx), p[1] - (a[1] + t * dy));
};
/**
 * Erases only what the eraser passes over: every visible stroke whose points come within `radius` of
 * the eraser path given for its display (page coordinates for content strokes, viewport coordinates
 * for screen strokes) is replaced by its surviving pieces. One gesture is one operation, whatever
 * displays it touched. Returns the document unchanged when nothing was touched.
 */
function erase(doc, paths, radius, at, newId) {
    const nearFor = (path) => !path || path.length === 0
        ? null
        : (p) => (path.length === 1 ? Math.hypot(p[0] - path[0][0], p[1] - path[0][1]) <= radius : path.some((a, i) => i > 0 && segmentDistance([p[0], p[1]], path[i - 1], a) <= radius));
    const nearBy = { content: nearFor(paths.content), screen: nearFor(paths.screen) };
    const boxOf = (pts, pad) => ({
        x0: Math.min(...pts.map((p) => p[0])) - pad,
        y0: Math.min(...pts.map((p) => p[1])) - pad,
        x1: Math.max(...pts.map((p) => p[0])) + pad,
        y1: Math.max(...pts.map((p) => p[1])) + pad,
    });
    const reach = { content: paths.content?.length ? boxOf(paths.content, radius) : null, screen: paths.screen?.length ? boxOf(paths.screen, radius) : null };
    const strokes = { ...doc.strokes };
    const added = [];
    const removed = [];
    for (const id of doc.visible) {
        const stroke = doc.strokes[id];
        const near = nearBy[stroke.display];
        const r = reach[stroke.display];
        if (!near || !r)
            continue;
        const b = boxOf(stroke.points, 0);
        if (b.x1 < r.x0 || b.x0 > r.x1 || b.y1 < r.y0 || b.y0 > r.y1)
            continue; // far from the eraser
        const points = densify(stroke.points, Math.max(0.5, radius / 2));
        if (!points.some(near))
            continue;
        removed.push(id);
        let run = [];
        const keep = () => {
            if (run.length >= 2) {
                const piece = { ...stroke, id: newId(), points: run, derived_from: stroke.derived_from ?? stroke.id };
                strokes[piece.id] = piece;
                added.push(piece.id);
            }
            run = [];
        };
        for (const p of points) {
            if (near(p))
                keep();
            else
                run.push(p);
        }
        keep();
    }
    if (removed.length === 0)
        return doc;
    return apply(doc, { at, op: 'erase', added, removed }, strokes);
}
function undo(doc, at) {
    const target = stacks(doc).undo.pop();
    if (target === undefined)
        return doc;
    const t = doc.history.find((op) => op.seq === target);
    return apply(doc, { at, op: 'undo', target_seq: target, added: [...t.removed], removed: [...t.added] });
}
function redo(doc, at) {
    const target = stacks(doc).redo.pop();
    if (target === undefined)
        return doc;
    const t = doc.history.find((op) => op.seq === target);
    return apply(doc, { at, op: 'redo', target_seq: target, added: [...t.added], removed: [...t.removed] });
}
const isObject = (v) => v !== null && typeof v === 'object' && !Array.isArray(v);
/** Reads a stored document strictly; anything unreadable is reported, never repaired or guessed. */
function parseInk(value, page) {
    if (!isObject(value) || value['format'] !== INK_FORMAT)
        return { ok: false, reason: 'the stored ink is not an lc-web-ink/v1 document' };
    const p = value['page'];
    if (!isObject(p) || p['address_sha256'] !== page.address_sha256 || p['origin'] !== page.origin)
        return { ok: false, reason: 'the stored ink belongs to another page' };
    const strokes = value['strokes'];
    const visible = value['visible'];
    const history = value['history'];
    if (!isObject(strokes) || !Array.isArray(visible) || !Array.isArray(history) || value['revision'] !== history.length)
        return { ok: false, reason: 'the stored ink is incomplete' };
    for (const [id, s] of Object.entries(strokes)) {
        if (!isObject(s) || s['id'] !== id || !['pen', 'mouse', 'touch'].includes(s['input']) || !['content', 'screen'].includes(s['display']))
            return { ok: false, reason: `stroke ${id} is malformed` };
        const pts = s['points'];
        if (!Array.isArray(pts) || pts.length === 0 || !pts.every((q) => Array.isArray(q) && q.length === 4 && q.every((n) => typeof n === 'number' && Number.isFinite(n))))
            return { ok: false, reason: `stroke ${id} has malformed points` };
        const a = s['anchor'];
        const rect = isObject(a) ? a['rect'] : null;
        const anchorOk = a === null ||
            (isObject(a) && typeof a['text_hash'] === 'string' && isObject(rect) && ['x', 'y', 'width', 'height'].every((k) => typeof rect[k] === 'number' && Number.isFinite(rect[k])) && (a['media_time'] === null || (typeof a['media_time'] === 'number' && Number.isFinite(a['media_time']))) && typeof a['opaque'] === 'boolean');
        if (!anchorOk)
            return { ok: false, reason: `stroke ${id} has a malformed anchor` };
        if (s['derived_from'] !== null && !(typeof s['derived_from'] === 'string' && Object.hasOwn(strokes, s['derived_from'])))
            return { ok: false, reason: `stroke ${id} is malformed` };
    }
    if (!visible.every((id) => typeof id === 'string' && Object.hasOwn(strokes, id)))
        return { ok: false, reason: 'the visible strokes are not all stored' };
    const doc = value;
    // Every operation must be what this module would have recorded, and the visible set must be what
    // the history produces.
    const known = (ids) => Array.isArray(ids) && ids.every((id) => typeof id === 'string' && Object.hasOwn(strokes, id));
    const same = (a, b) => a.length === b.length && a.every((id, i) => id === b[i]);
    let replay = { ...emptyInk(page), strokes: doc.strokes };
    for (const [i, op] of doc.history.entries()) {
        if (!isObject(op) || op.seq !== i + 1 || typeof op.at !== 'string' || !known(op.added) || !known(op.removed))
            return { ok: false, reason: 'the stored history is malformed' };
        if (op.op === 'undo' || op.op === 'redo') {
            const s = stacks(replay);
            const targetSeq = op.op === 'undo' ? s.undo.at(-1) : s.redo.at(-1);
            const t = replay.history.find((h) => h.seq === targetSeq);
            const [added, removed] = t ? (op.op === 'undo' ? [t.removed, t.added] : [t.added, t.removed]) : [[], []];
            if (!t || op.target_seq !== targetSeq || !same(op.added, added) || !same(op.removed, removed))
                return { ok: false, reason: 'the stored history is malformed' };
        }
        else if (op.op === 'add') {
            // One new stroke, hiding nothing.
            if (op.added.length !== 1 || op.removed.length !== 0 || replay.history.some((h) => h.added.includes(op.added[0])))
                return { ok: false, reason: 'the stored history is malformed' };
        }
        else if (op.op === 'erase') {
            // Visible strokes replaced by new pieces derived from them.
            const ok = op.removed.length > 0 && op.removed.every((id) => replay.visible.includes(id)) && op.added.every((id) => doc.strokes[id].derived_from !== null && !replay.history.some((h) => h.added.includes(id)));
            if (!ok)
                return { ok: false, reason: 'the stored history is malformed' };
        }
        else {
            return { ok: false, reason: 'the stored history is malformed' };
        }
        replay = apply(replay, op, doc.strokes);
    }
    if (!same(replay.visible, doc.visible))
        return { ok: false, reason: 'the stored visible strokes (or their drawing order) do not match their history' };
    return { ok: true, doc };
}
const INK_COPY_KIND = 'lc-web-ink-copy/v1';
/** Whether a value describes a copy the way this version writes it. */
function isCopy(v) {
    if (!isObject(v))
        return false;
    const { id, reason, created_at: createdAt, forked_from: forkedFrom, forked_at: forkedAt } = v;
    const copyId = (x) => typeof x === 'string' && /^[0-9a-f]{16}$/.test(x);
    return (copyId(id) &&
        (reason === 'conflict' || reason === 'unreadable' || reason === 'unloaded') &&
        typeof createdAt === 'string' &&
        createdAt.length <= 40 &&
        (forkedFrom === null || copyId(forkedFrom)) &&
        (forkedAt === null || (Number.isSafeInteger(forkedAt) && forkedAt >= 0)));
}
/** The stored form of a copy: its description (only the fields of InkCopy) and the whole document. */
const copyRecord = (copy, doc) => ({
    kind: INK_COPY_KIND,
    id: copy.id,
    reason: copy.reason,
    created_at: copy.created_at,
    forked_from: copy.forked_from,
    forked_at: copy.forked_at,
    doc,
});
/** Reads a stored copy strictly (its description and its document, with parseInk). */
function parseCopy(value, page) {
    if (!isObject(value) || value['kind'] !== INK_COPY_KIND || !isCopy(value))
        return { ok: false, reason: 'the stored copy is not an lc-web-ink-copy/v1 record' };
    const parsed = parseInk(value['doc'], page);
    if (!parsed.ok)
        return parsed;
    const { id, reason, created_at: createdAt, forked_from: forkedFrom, forked_at: forkedAt } = value;
    return { ok: true, copy: { id, reason, created_at: createdAt, forked_from: forkedFrom, forked_at: forkedAt }, doc: parsed.doc };
}

exports.INK_FORMAT = INK_FORMAT;
exports.emptyInk = emptyInk;
exports.stacks = stacks;
exports.addStroke = addStroke;
exports.erase = erase;
exports.undo = undo;
exports.redo = redo;
exports.parseInk = parseInk;
exports.INK_COPY_KIND = INK_COPY_KIND;
exports.isCopy = isCopy;
exports.copyRecord = copyRecord;
exports.parseCopy = parseCopy;
});
factories.set("apps/safari-extension/src/ink-worker.js", (exports, require) => {
// Background entry of the WebExtension (generated as webextension/ink-format.js, loaded with
// importScripts): the ink document reader, so the background checks stored and incoming ink with
// exactly the code the page uses.
const { copyRecord, isCopy, parseCopy, parseInk } = require("apps/safari-extension/src/ink.js");
globalThis.lcInkFormat = { parseInk, parseCopy, isCopy, copyRecord };

});
require("apps/safari-extension/src/ink-worker.js");
})();
