$ErrorActionPreference = 'Stop'
try { [Console]::OutputEncoding = [Text.Encoding]::UTF8 } catch { }
$out = [ordered]@{ powershell = $PSVersionTable.PSVersion.ToString(); edition = [string]$PSVersionTable.PSEdition; ui_culture = [string][Threading.Thread]::CurrentThread.CurrentUICulture }
$points = @(); try {     for ($card = 0; $card -lt 12; $card++) { $points += ,@((40 + $card % 4 * 210 + 95) * 2, (90 + [Math]::Floor($card / 4) * 170 + 75) * 2) }; $out.old_line = 'no error' } catch { $out.old_line = $_.Exception.GetType().FullName + ' | ' + $_.Exception.Message; $out.old_line_card = $card }
[Threading.Thread]::CurrentThread.CurrentUICulture = [Globalization.CultureInfo]::GetCultureInfo('en-US'); $points = @(); try {     for ($card = 0; $card -lt 12; $card++) { $points += ,@((40 + $card % 4 * 210 + 95) * 2, (90 + [Math]::Floor($card / 4) * 170 + 75) * 2) }; $out.old_line_en = 'no error' } catch { $out.old_line_en = $_.Exception.Message }
$e = $null; $t = $null; $a = [Management.Automation.Language.Parser]::ParseInput('(40 + $card % 4 * 210 + 95) * 2, (90 + [Math]::Floor($card / 4) * 170 + 75) * 2', [ref]$t, [ref]$e); $x = $a.EndBlock.Statements[0].PipelineElements[0].Expression; $out.old_parse = [ordered]@{ errors = @($e).Count; top = $x.GetType().Name; operator = [string]$x.Operator; left = $x.Left.GetType().Name; left_text = $x.Left.Extent.Text; right = $x.Right.GetType().Name; right_text = $x.Right.Extent.Text }
$e = $null; $t = $null; $a = [Management.Automation.Language.Parser]::ParseInput('((40 + $card % 4 * 210 + 95) * 2), ((90 + [Math]::Floor($card / 4) * 170 + 75) * 2)', [ref]$t, [ref]$e); $x = $a.EndBlock.Statements[0].PipelineElements[0].Expression; $out.new_parse = [ordered]@{ errors = @($e).Count; top = $x.GetType().Name; elements = @($x.Elements | ForEach-Object { $_.GetType().Name }) }
$points = @(); try {     for ($card = 0; $card -lt 12; $card++) { $points += ,@(((40 + $card % 4 * 210 + 95) * 2), ((90 + [Math]::Floor($card / 4) * 170 + 75) * 2)) }; $out.new_line = 'no error' } catch { $out.new_line = $_.Exception.Message }
    $points += ,@(20, 20); $points += ,@(2540, 20); $points += ,@(20, 1580); $points += ,@(2540, 1580)
$out.new_count = $points.Count; $out.new_pair_lengths = @($points | ForEach-Object { @($_).Count } | Sort-Object -Unique); $out.new_points = @($points | ForEach-Object { '{0},{1}' -f [int]$_[0], [int]$_[1] }); $out.new_types = @($points[0] | ForEach-Object { $_.GetType().Name })
$arith = 'Plus', 'Minus', 'Multiply', 'Divide', 'Rem'
$files = [ordered]@{ r2_attempt1 = '\\wsl.localhost\Ubuntu\home\agentsdock\Projects\learning-companion\wt-review\docs\verification\qa\p0-13-tts-52be105\candidate-edge-identity-r2-20261008\runner.ps1'; r3 = '\\wsl.localhost\Ubuntu\home\agentsdock\Projects\learning-companion\wt-review\docs\verification\qa\p0-13-tts-52be105\candidate-r3-20261008\runner.ps1' }
$out.files = [ordered]@{}; foreach ($k in $files.Keys) { $e = $null; $t = $null; $f = [Management.Automation.Language.Parser]::ParseFile($files[$k], [ref]$t, [ref]$e); $h = $f.FindAll({ param($n) $n -is [Management.Automation.Language.BinaryExpressionAst] -and $arith -contains [string]$n.Operator -and ($n.Left -is [Management.Automation.Language.ArrayLiteralAst] -or $n.Right -is [Management.Automation.Language.ArrayLiteralAst]) }, $true); $fn = $f.Find({ param($n) $n -is [Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Assert-QaProductPlacement' }, $true); $assigns = @($fn.FindAll({ param($n) $n -is [Management.Automation.Language.AssignmentStatementAst] -and $n.Left -is [Management.Automation.Language.VariableExpressionAst] }, $true) | ForEach-Object { $_.Left.VariablePath.UserPath } | Sort-Object -Unique); $readers = @($f.FindAll({ param($n) $n -is [Management.Automation.Language.FunctionDefinitionAst] }, $true) | Where-Object { $_.Body.FindAll({ param($v) $v -is [Management.Automation.Language.VariableExpressionAst] -and $v.VariablePath.UserPath -eq 'client' }, $true).Count -gt 0 } | ForEach-Object { $_.Name }); $out.files[$k] = [ordered]@{ parse_errors = @($e).Count; array_arith_hits = @($h | ForEach-Object { [ordered]@{ line = $_.Extent.StartLineNumber; operator = [string]$_.Operator; text = $_.Extent.Text } }); product_placement_assigns = $assigns; functions_using_client = $readers } }
$out | ConvertTo-Json -Depth 6
