import subprocess, sys, signal, os
signal.signal(signal.SIGTERM, lambda *a: sys.exit(1))
ROOT=os.environ['LC_MUT_ROOT']  # a SCRATCH copy of apps/windows (src, tests, node_modules): its sources are rewritten and restored
os.chdir(ROOT)
M='src/main/main.ts'; O='src/renderer/overlay.ts'; C='src/renderer/control.ts'; L='src/shared/live.ts'
T='tests/app-live.test.ts tests/app-ask.test.ts tests/overlay-surfaces.test.ts tests/control-live.test.ts tests/live.test.ts'
MUT=[
 ('look-after-end', M, [("  if (!subscription || !live || live.ended !== null || s.ending || current !== s) return;\n  if (Date.parse", "  if (!subscription || !live || s.ending || current !== s) return;\n  if (Date.parse")]),
 ('look-while-ending', M, [("  if (!subscription || !live || live.ended !== null || s.ending || current !== s) return;\n  if (Date.parse", "  if (!subscription || !live || live.ended !== null || current !== s) return;\n  if (Date.parse")]),
 ('paused-no-gap', M, [("  if (live.paused !== null) return void gap(s, live, seq, 'budget');", "  if (live.paused !== null) return;")]),
 ('replaced-no-gap', M, [("  if (live.waiting) gap(s, live, live.waiting.context.frame_seq, 'coalesced');\n  live.waiting = { context", "  live.waiting = { context")]),
 ('two-looks-at-once', M, [("if (!w || live.ended !== null || live.paused !== null || live.out > 0 || live.cooling) return;", "if (!w || live.ended !== null || live.paused !== null || live.cooling) return;")]),
 ('no-interval', M, [("if (!w || live.ended !== null || live.paused !== null || live.out > 0 || live.cooling) return;", "if (!w || live.ended !== null || live.paused !== null || live.out > 0) return;")]),
 ('flush-after-end', M, [("if (!w || live.ended !== null || live.paused !== null || live.out > 0 || live.cooling) return;", "if (!w || live.paused !== null || live.out > 0 || live.cooling) return;")]),
 ('reserve-off-by-one', M, [("  if (live.used >= live.policy.max_submissions - reserveOf(live.policy.max_submissions)) {", "  if (live.used > live.policy.max_submissions - reserveOf(live.policy.max_submissions)) {")]),
 ('no-reserve', M, [("  if (live.used >= live.policy.max_submissions - reserveOf(live.policy.max_submissions)) {", "  if (false) {")]),
 ('reserve-no-gap', M, [("    live.paused = 'the requests left in this session are kept for your own focus and follow-ups';\n    gap(s, live, w.context.frame_seq, 'budget');", "    live.paused = 'the requests left in this session are kept for your own focus and follow-ups';")]),
 ('no-cooling', M, [("  live.cooling = true;\n  setTimeout(() => {", "  setTimeout(() => {")]),
 ('cooling-forever', M, [("    live.cooling = false;\n    flushLook(s, live);\n  }, live.policy.min_observation_interval_ms);", "    flushLook(s, live);\n  }, live.policy.min_observation_interval_ms);")]),
 ('no-flush-after-cooling', M, [("    live.cooling = false;\n    flushLook(s, live);\n  }, live.policy.min_observation_interval_ms);", "    live.cooling = false;\n  }, live.policy.min_observation_interval_ms);")]),
 ('look-not-in-history', M, [("    live.history.push({ kind: 'observation', text: out.answer.text,", "    void ({ kind: 'observation', text: out.answer.text,")]),
 ('look-as-shown', M, [("request_id: t.request_id, audio_source: null, presentation: 'not_presented' });\n    appendLive(s, live, { kind: 'looked'", "request_id: t.request_id, audio_source: null, presentation: 'shown' });\n    appendLive(s, live, { kind: 'looked'")]),
 ('no-seen', M, [("    live.seen = { at: new Date().toISOString(), frame_seq: seq };", "")]),
 ('reserved-no-pause', M, [("    if (reserved && live.ended === null && live.paused === null) live.paused = 'the requests left in this session are kept for your own focus and follow-ups';", "")]),
 ('gap-reason-flat', M, [("reserved ? 'budget' : out.status === 'refused' && (out.code === 'busy' || out.code === 'stale_context') ? 'backpressure' : 'not_observed'", "'not_observed'")]),
 ('no-flush-after-look', M, [("  notifyLive(s);\n  flushLook(s, live);\n}\n/** Where and when a whole frame was taken", "  notifyLive(s);\n}\n/** Where and when a whole frame was taken")]),
 ('count-always', M, [("  if (out.submission !== 'not_submitted') live.used += 1;", "  live.used += 1;")]),
 ('count-never', M, [("  if (out.submission !== 'not_submitted') live.used += 1;", "")]),
 ('failure-goes-on', M, [("    if (failed !== null) endLive(s, live, `${failed}; nothing more is sent by itself`);", "")]),
 ('uncertain-goes-on', M, [("    const failed = out.status === 'uncertain' ? out.reason\n", "    const failed = out.status === 'uncertain' ? null\n")]),
 ('end-no-stop', M, [("  subscription?.stopSession(live.id); // told to the connector that has it; its turns that are out are interrupted\n", "")]),
 ('end-no-hush', M, [("  if (s.live === live) hush(s);\n  appendLive(s, live, { kind: 'ended'", "  appendLive(s, live, { kind: 'ended'")]),
 ('end-keeps-waiting', M, [("  if (live.waiting) gap(s, live, live.waiting.context.frame_seq, 'not_observed');\n  live.waiting = null;\n  live.latest = null;", "  live.latest = null;")]),
 ('end-twice', M, [("  if (live.ended !== null) return;\n  live.ended = reason;", "  live.ended = reason;")]),
 ('restart-keeps-old', M, [("  if (s.live && s.live.ended === null) endLive(s, s.live, 'all of its requests were used, and you started the AI again'); // one session at a time (said as what is true whatever the new Start comes to)\n", "")]),
 ('start-twice', M, [("  if (!subscription || s.liveStarting || (s.live && s.live.ended === null && s.live.used < s.live.policy.max_submissions) || s.ending || current !== s) return;", "  if (!subscription || s.liveStarting || s.ending || current !== s) return;")]),
 ('no-expiry', M, [("  setTimeout(() => endLive(s, live, 'this session\\'s time is over'), r.expires_in_ms);\n", "")]),
 ('not-started-silent', M, [("    s.liveOff = r.reason;\n    appendLive(s, null, { kind: 'not_started'", "    appendLive(s, null, { kind: 'not_started'")]),
 ('passed-gap-dropped', M, [("...(passed ? [passed] : []), ...left];", "...left];")]),
 ('omitted-gap-dropped', M, [("...(passed ? [passed] : []), ...left];", "...(passed ? [passed] : [])];")]),
 ('later-gaps-sent', M, [("(g.from_frame_seq >= seq ? [] : [{ ...g, to_frame_seq: Math.min(g.to_frame_seq, seq - 1) }])", "[g]")]),
 ('frame-not-counted', M, [("  if (live) live.frames += 1; // (a frame of the session: counted once it is kept)\n", "")]),
 ('circle-explain', M, [("const request = submitTurn(s, sel, 'focus', null, 'hint', frame, kept);", "const request = submitTurn(s, sel, 'focus', null, 'explain', frame, kept);")]),
 ('circle-unsent-no-gap', M, [("  if (!request.ok && live && live.ended === null) gap(s, live, frame.context.frame_seq, 'not_observed'); // a frame of the session the AI was not given\n", "")]),
 ('same-always', M, [("  if (usable && unchanged && live.latest === sel.sent!.frame) return submitTurn(", "  if (usable) return submitTurn(")]),
 ('same-never', M, [("  if (usable && unchanged && live.latest === sel.sent!.frame) return submitTurn(", "  if (false) return submitTurn(")]),
 ('same-ignores-newer', M, [("  if (usable && unchanged && live.latest === sel.sent!.frame) return submitTurn(", "  if (usable && unchanged) return submitTurn(")]),
 ('same-ignores-picture', M, [("  if (usable && unchanged && live.latest === sel.sent!.frame) return submitTurn(", "  if (usable && live.latest === sel.sent!.frame) return submitTurn(")]),
 ('same-ignores-ink', M, [(" && read.frame.context.ink_revision === sel.frame.context.ink_revision && read.frame.context.ink_sha256 === sel.frame.context.ink_sha256;", ";")]),
 ('followup-frame-not-counted', M, [("    live.frames += 1;\n    keptNow = true;", "    keptNow = true;")]),
 ('followup-unsent-no-gap', M, [("  if (!sent.ok && keptNow && live.ended === null) gap(s, live, read.frame.context.frame_seq, 'not_observed'); // kept, and not given to the AI\n", "")]),
 ('no-carry', M, [("    if (typeof carried !== 'string') {\n      t = carried;", "    if (false) {\n      t = carried as Turn;")]),
 ('always-spoken', M, [("  const asked_as = voice !== null && s.talk.on && !s.talk.muted ? 'spoken' : 'silent';", "  const asked_as = 'spoken';")]),
 ('never-spoken', M, [("  const asked_as = voice !== null && s.talk.on && !s.talk.muted ? 'spoken' : 'silent';", "  const asked_as = 'silent';")]),
 ('origin-of-followup', M, [("  if (t.focus !== null && (trigger === 'focus' || anew !== null)) {", "  if (t.focus !== null) {")]),
 ('no-origin', M, [("  if (t.focus !== null && (trigger === 'focus' || anew !== null)) {", "  if (false) {")]),
 ('no-flush-after-ask', M, [("gap(s, live, seq, out.status === 'refused' && (out.code === 'busy' || out.code === 'stale_context') ? 'backpressure' : 'not_observed');\n    flushLook(s, live);", "gap(s, live, seq, out.status === 'refused' && (out.code === 'busy' || out.code === 'stale_context') ? 'backpressure' : 'not_observed');")]),
 ('waiting-kept-after-ask', M, [("  if (passed !== null) {\n    gap(s, live, passed, 'coalesced');\n    live.waiting = null;\n  }", "  if (passed !== null) gap(s, live, passed, 'coalesced');")]),
 ('shown-after-session-end', M, [("const current_ = current === s && !s.ending && s.live === live && live.ended === null && s.ask === sel", "const current_ = current === s && !s.ending && s.ask === sel")]),
 ('no-user-history', M, [("    if (t.user_text !== null) live.history.push({ kind: 'user'", "    if (false) live.history.push({ kind: 'user'")]),
 ('no-assistant-history', M, [("    live.history.push(said);\n    presented.set(entry, said);", "    presented.set(entry, said);")]),
 ('history-not-updated-shown', M, [("    const said = presented.get(entry);\n    if (said) said.presentation = 'shown';", "")]),
 ('speak-always', M, [("speak: view.status === 'answered' && t.presentation === 'spoken' });", "speak: view.status === 'answered' });")]),
 ('used-up-sends', M, [("  if (s.live.used >= s.live.policy.max_submissions) return 'all of this AI session\\'s requests are used; start the AI again in the control window';\n", "")]),
 ('read-after-session-end', M, [("  if (s.ending || !s.live || s.live.ended !== null || !s.talk.on", "  if (s.ending || !s.talk.on")]),
 ('read-silent-asked', M, [(" || entry.presentation !== 'shown' || entry.asked_as !== 'spoken') return null;", " || entry.presentation !== 'shown') return null;")]),
 ('start-any-policy', M, [("(isObj(ai) && Object.keys(ai).join() === 'policy' && isPolicy(ai['policy']))", "(isObj(ai) && isObj(ai['policy']))")]),
 ('live-start-any-sender', M, [("  if (!fromControl(e) || !isPolicy(policy)) return { ok: false, reason: 'refused' };", "  if (!isPolicy(policy)) return { ok: false, reason: 'refused' };")]),
 ('live-start-any-policy', M, [("  if (!fromControl(e) || !isPolicy(policy)) return { ok: false, reason: 'refused' };", "  if (!fromControl(e)) return { ok: false, reason: 'refused' };")]),
 ('live-stop-any-sender', M, [("ipcMain.on('lc:live-stop', (e) => void (fromControl(e) && current?.live", "ipcMain.on('lc:live-stop', (e) => void (current?.live")]),
 ('lost-connector-goes-on', M, [("        if (s?.live && s.live.ended === null && !subscription?.sessionLive(s.live.id)) endLive(s, s.live, 'the connection to ChatGPT was lost');", "")]),
 ('no-used-up-state', M, [("l.ended !== null ? 'ended' : l.used >= max ? 'used_up' : 'on'", "l.ended !== null ? 'ended' : 'on'")]),
 ('stop-keeps-session', M, [("  if (s.live && s.live.ended === null) endLive(s, s.live, why);", "")]),
 ('attempt-as-interrupted', M, [("said === r.pieces.length ? 'finished' : over && said > 0 ? 'interrupted' : 'attempted';", "said === r.pieces.length ? 'finished' : over ? 'interrupted' : 'attempted';")]),
 ('quit-first-rejection', M, [("Promise.allSettled([link?.quit(20_000), subscription?.quit(), endVoice()])", "Promise.all([link?.quit(20_000), subscription?.quit(), endVoice()]).catch(() => undefined)")]),
 ('voice-end-unbounded', M, [("    setTimeout(done, VOICE_END_MS);\n", "")]),
 ('focus-from-overlay-px', M, [("  const focus = focusOf({ x: f['region_dip'].x, y: f['region_dip'].y, width: f['region_dip'].width, height: f['region_dip'].height }, { width: frame.image.width, height: frame.image.height, seq: frame.context.frame_seq }, s.display.bounds);", "  const focus = focusOf({ x: f['region_dip'].x, y: f['region_dip'].y, width: f['region_dip'].width, height: f['region_dip'].height }, { width: s.display.bounds.width, height: s.display.bounds.height, seq: frame.context.frame_seq }, s.display.bounds);")]),
 ('page-speaks-unasked', O, [("  if (out.status === 'answered' && a.selection && record.speak === true) speak(", "  if (out.status === 'answered' && a.selection) speak(")]),
 ('page-early-any-selection', O, [("  if (early && early.selection === a.selection && early.request === a.request) return showOutcome(a, early.outcome, early.record);", "  if (early) return showOutcome(a, early.outcome, early.record);")]),
 ('page-cancel-lost', O, [("  if (a.cancelling) return void lc.askCancel(a.selection); // cancelled before its selection was known here: said to the main process now", "  if (a.cancelling) return;")]),
 ('page-encode-silent', O, [("      failed = `The picture of the display could not be made (${why(error)}), so this selection was not kept and nothing was sent to any AI.\\n`;", "      throw error;")]),
 ('page-no-live-update', O, [("lc.onLive((next) => {\n  live = next;\n  render();\n});", "lc.onLive(() => undefined);")]),
 ('page-question-kept', O, [("  a.about = sent.about;\n  $<HTMLTextAreaElement>('question').value = '';", "  a.about = sent.about;")]),
 ('control-clamps', C, [("  if (!whole(requests, POLICY_LIMITS.requests)) return", "  if (false) return")]),
 ('control-credits-zero', C, [("    const credits = w.credits === null ? 'credits not reported'", "    const credits = w.credits === null ? 'credits: none'")]),
 ('control-unavailable-zero', C, [("  if (!q.available) return `Usage as ChatGPT reported it${at}: not available then (not known; this is not zero).`;", "")]),
 ('fix-no-looks-closed', M, [("    r.closed = full;\n    looksClosed(s);\n", "    r.closed = full;\n")]),
 ('fix-new-session-not-closed', M, [("  looksClosed(s); // (a capture that keeps no further frame gives this session none to look at by itself: said from the start)\n", "")]),
 ('fix-unsettled-goes-on', M, [("      : out.status === 'cancelled' && out.unsettled ? 'a request was interrupted, and whether ChatGPT stopped working on it is not confirmed' : null;", "      : null;")]),
 ('fix-paused-keeps-waiting', M, [("    if (live.paused !== null && live.waiting) {\n      gap(s, live, live.waiting.context.frame_seq, 'budget');\n      live.waiting = null;\n    }", "")]),
 ('fix-flush-ignores-paused', M, [("if (!w || live.ended !== null || live.paused !== null || live.out > 0 || live.cooling) return;", "if (!w || live.ended !== null || live.out > 0 || live.cooling) return;")]),
 ('fix-earlier-frames-looked', M, [("  if (Date.parse(capturedAt) < live.since) return;", "")]),
 ('fix-torn-not-cut', M, [("    if (size > s.liveBytes) truncateSync(file, s.liveBytes); // a torn line: only whole lines are kept\n", "")]),
 ('fix-unwritten-not-counted', M, [("    s.liveUnwritten += 1;\n", "")]),
 ('fix-unwritten-not-said-after-end', M, [("ended: lastEnd, live_unwritten: lastEnded?.liveUnwritten ?? 0 }", "ended: lastEnd, live_unwritten: 0 }")]),
 ('fix-no-settled', M, [("  if (live.ended !== null) appendLive(s, live, { kind: 'settled'", "  if (false) appendLive(s, live, { kind: 'settled'")]),
 ('fix-restart-keeps-ended', M, [("    s.live = null;\n    s.liveOff = r.reason;", "    s.liveOff = r.reason;")]),
 ('fix-own-frame-gap', M, [("(g.from_frame_seq >= seq ? [] : [{ ...g, to_frame_seq: Math.min(g.to_frame_seq, seq - 1) }])", "(g.to_frame_seq > seq ? [] : [g])")]),
 ('fix-not-taken-no-gap', M, [("    else if (live.ended === null && !live.gaps.some(covers) && !live.history.some((h) => h.frame_seq === seq && h.kind !== 'user')) gap(", "    else if (false) gap(")]),
 ('fix-answered-keeps-gap', M, [("    if (out.status === 'answered') live.gaps = live.gaps.flatMap(", "    if (false) live.gaps = live.gaps.flatMap(")]),
 ('fix-no-anew', M, [("  const anew = unchanged && !usable ? focusOf(", "  const anew = false ? focusOf(")]),
 ('fix-store-before-check', M, [("  const unkept = keep?.() ?? null;\n  if (unkept !== null) return { ok: false, reason: unkept };\n", "  void keep;\n")]),
 ('fix-page-cancel-while-encoding', O, [("  if (a.cancelling || ended) {\n    a.cancelling = false;\n    return notSent(", "  if (false) {\n    a.cancelling = false;\n    return notSent(")]),
 ('fix-page-still-shown', O, [("${answerShown && a.shown ? ` The response still shown is the one before: ${a.shown}` : ''}", "")]),
 ('fix-page-submission', O, [("out.submission === 'not_submitted' ? 'It did not reach ChatGPT' : out.submission === 'submitted' ? 'It had reached ChatGPT' : 'Whether it reached ChatGPT is not known'", "'It had reached ChatGPT'")]),
 ('fix-box-reticked', C, [("  if (aiOffered) aiWanted = box.checked;\n  box.checked = can && aiWanted;", "  box.checked = can;")]),
 ('fix-start-ignores-box', C, [("  if ($('aiSession').hidden || box.disabled || !box.checked) return { ai: null };", "  if ($('aiSession').hidden || box.disabled) return { ai: null };")]),
 ('fix-start-ignores-disabled', C, [("  if ($('aiSession').hidden || box.disabled || !box.checked) return { ai: null };", "  if ($('aiSession').hidden || !box.checked) return { ai: null };")]),
 ('fix-buttons-not-hidden', C, [("    for (const id of ['liveActions', 'liveStart', 'liveStop']) $(id).hidden = true;\n    return;", "    $('liveActions').hidden = true;\n    return;")]),
 ('fix-quota-now', C, [("'included usage was allowed then'", "'included usage is allowed now'")]),
 ('fix-history-one-range', L, [("    if (last && ![...sent].some((k) => k !== null && k > last.to_frame_seq && k < n)) last.to_frame_seq = n;", "    if (last) last.to_frame_seq = n;")]),
 ('fix-history-names-sent-frame', L, [("filter((x): x is number => x !== null && !sent.has(x))", "filter((x): x is number => x !== null)")]),
]
only=sys.argv[1:]
lo,hi=(int(only[0]),int(only[1])) if len(only)==2 and only[0].isdigit() else (0,len(MUT))
if only and only[0]=='count': print(len(MUT)); sys.exit(0)
for name,f,pairs in MUT[lo:hi]:
    src=open(f).read(); m=src; bad=False
    for a,b in pairs:
        if m.count(a)!=1: print(name,'PATTERN',m.count(a),a[:70]); bad=True; break
        m=m.replace(a,b)
    if bad: continue
    open(f,'w').write(m)
    try:
        r=subprocess.run(['timeout','60','node','--test']+T.split(),capture_output=True,text=True)
        print(name,'KILLED' if r.returncode else 'SURVIVED', flush=True)
    finally:
        open(f,'w').write(src)
